services:
  - name: bongao-bakery-backend
    type: web
    env: python
    pythonVersion: "3.11"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT
    healthcheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bongao-bakery-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: https://bongao-bakery-frontend.vercel.app
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"