services:
  - type: web
    name: bongao-bakery-backend
    env: python
    python:
      version: "3.10.13"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PIP_NO_BUILD_ISOLATION
        value: "0"
      - key: CARGO_NET_OFFLINE
        value: "true"